[package]
name   ="notary"
version="0.6.0"
edition="2021"
build  ="build.rs"

[features]
default                                      =["tee-dummy-token-generator"]
tee-dummy-token-generator                    =[]
tee-google-confidential-space-token-generator=[]

[dependencies]
client-side-prover   ={ workspace=true }
proofs               ={ workspace=true }
client               ={ workspace=true }
hyper                ={ workspace=true, features=["client", "http1", "server"] }
hyper-util           ={ workspace=true }
serde                ={ workspace=true }
serde_json           ={ workspace=true }
rustls               ={ workspace=true, features=["logging", "tls12", "std", "ring"] }
tokio                ={ workspace=true }
tokio-util           ={ workspace=true, features=["compat"] }
tracing              ={ workspace=true }
tracing-subscriber   ={ workspace=true }
futures              ={ workspace=true }
futures-util         ={ workspace=true }
tokio-rustls         ={ workspace=true, features=["ring"] }
tower-http           ={ workspace=true, features=["cors"] }
tower-service        ={ workspace=true }
rustls-pemfile       ={ workspace=true }
tlsn-verifier        ={ workspace=true }
tokio-tungstenite    ={ workspace=true, features=["stream"] }
ws_stream_tungstenite={ workspace=true, features=["tokio"] }
nom                  ={ workspace=true }

async-trait     ={ workspace=true }
axum            ={ workspace=true, features=["ws", "json"] }
axum-core       ={ workspace=true }
eyre            ={ workspace=true }
p256            ={ workspace=true }
base64          ={ workspace=true }
http            ={ workspace=true }
sha1            ={ workspace=true }
config          ={ workspace=true }
clap            ={ workspace=true }
rustls-acme     ={ workspace=true, features=["ring", "tokio"] }
tokio-stream    ={ workspace=true, features=["net"] }
thiserror       ={ workspace=true }
hex             ={ workspace=true }
tls-parser      ={ workspace=true }
rs_merkle       ={ workspace=true }
alloy-primitives={ workspace=true, features=["k256"] }
k256            ={ workspace=true, features=["ecdsa"] }
reqwest         ={ workspace=true, features=["json"] }
uuid            ={ workspace=true }

tls-client2={ workspace=true }

caratls_ekm_server                          ={ workspace=true }
caratls_ekm_google_confidential_space_server={ workspace=true }
web-proof-circuits-witness-generator        ={ workspace=true }

[dev-dependencies]
tower={ workspace=true }

[build-dependencies]
cargo_metadata={ workspace=true }
