[workspace]
members=["client", "client_ios", "client_wasm", "notary"]
# members =["client", "client_wasm"] # config for wasm32 rust analyzer
# members =["client", "client_ios"] # config for ios rust analyzer
resolver="2"

[patch.'https://github.com/tlsnotary/tlsn.git']
tls-client      ={ path="tls/tls-client" }
tls-client-async={ path="tls/tls-client-async" }

[workspace.dependencies]
# Local re-exporting
client={ path="client" }
# Serde
serde     ={ version="1.0.204", features=["derive"] }
serde_json="1.0.120"
# Logging
tracing           ="0.1.40"
tracing-subscriber={ version="0.3.18", features=["env-filter"] }

notary-server={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4" }
tlsn-verifier={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4" }
tlsn-prover={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4", features=[
	"tracing",
] }
tlsn-core={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4" }
tls-client={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4", package="tlsn-tls-client" }

# rand
rand       ="0.8"
rand_chacha="0.3"

# crypto
aes         ="0.8"
aes-gcm     ="0.9"
sha2        ="0.10"
hmac        ="0.12"
sct         ="0.7"
digest      ="0.10"
webpki      ="0.22"
webpki-roots="0.26"

ring={ version="0.17", features=["wasm32_unknown_unknown_js"] }

p256          ="0.13"
rustls-pemfile="1"
rustls        ="0.20"
async-rustls  ="0.4"

# async
async-trait="0.1"
futures    ="0.3"
tokio      ="1"
tokio-util ="0.7"
hyper      ="0.14"

# serialization
bytes="1"
# serde="1"

# error/log
# tracing           ="0.1"
# tracing-subscriber="0.3"
thiserror ="1"
log       ="0.4"
env_logger="0.10"

# testing
rstest="0.12"

# misc
derive_builder   ="0.12"
enum-try-as-inner="0.1"
web-time         ="0.2"

[package]
name   ="webprover"
edition="2021"

[[bin]]
name="origo"
path="bin/origo.rs"

[[bin]]
name="mock_server"
path="bin/mock_server.rs"

# Can use something like this for e2e testing of the workspace
# https://doc.rust-lang.org/cargo/reference/manifest.html
# [[test]]

[dependencies]
# Dependancies for the binaries
tokio            ={ version="1.39.0", features=["full"] }
hyper            ={ version="1.4.1", features=["full"] }
hyper-util       ={ version="0.1.6", features=["full"] }
http-body-util   ="0.1"
pki-types        ={ package="rustls-pki-types", version="1.7" }
rustls           ={ version="0.23.11", default-features=false, features=["logging", "tls12", "std", "ring"] }
rustls-pemfile   ={ version="2.0.0" }
tokio-rustls     ={ version="0.26.0", default-features=false, features=["logging", "tls12"] }
hex              ="0.4"
futures-util     ="0.3"
form_urlencoded  ="1.2.1"
tokio-tungstenite="0.23.0"

# TODO how to get symbols for debugging (stack trace) into wasm module in --release mode?
# [profile.release]
# debug = true
