[workspace]
members=["client", "client_ios", "client_wasm", "notary", "proofs"]
# members =["client", "client_wasm", "proofs"] # config for wasm32 rust analyzer
# members =["client", "client_ios"] # config for ios rust analyzer
resolver="2"

[workspace.metadata]
# https://github.com/pluto/web-prover-circuits/releases
web_prover_circuits_version="0.10.0"

[workspace.dependencies]
# Local re-exporting
client={ path="client" }
proofs={ path="proofs" }
# Serde
serde     ={ version="1.0.204", features=["derive"] }
serde_json="1.0.120"
# Logging
tracing="0.1.40"
tracing-subscriber={ version="0.3.18", features=["env-filter"] }
tlsn-verifier={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4" }
tlsn-prover={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4", features=[
  "tracing",
] }
tlsn-core={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4" }
tls-client={ git="https://github.com/tlsnotary/tlsn.git", tag="v0.1.0-alpha.4", package="tlsn-tls-client" }

tls-client2       ={ git="https://github.com/pluto/tls-origo-legacy", package="tls-client" }
tls-core          ={ git="https://github.com/pluto/tls-origo-legacy", package="tls-core" }
rayon             ="1.10.0"
wasm-bindgen-rayon="=1.2.1"
futures           ="0.3"

caratls_ekm_server                          ={ git="https://github.com/pluto/caratls.git", rev="2f4631af7400eafec7a533b72d1d460fa5a66db3" }
caratls_ekm_google_confidential_space_server={ git="https://github.com/pluto/caratls.git", rev="2f4631af7400eafec7a533b72d1d460fa5a66db3" }
caratls_ekm_client                          ={ git="https://github.com/pluto/caratls.git", rev="2f4631af7400eafec7a533b72d1d460fa5a66db3" }
caratls_ekm_google_confidential_space_client={ git="https://github.com/pluto/caratls.git", rev="2f4631af7400eafec7a533b72d1d460fa5a66db3" }

# CLI
clap={ version="4.5.13", features=["derive"] }
# errors
thiserror="1.0.61"

# HTTP
hyper         ={ version="1.6", features=["full"] }
hyper-util    ={ version="0.1", features=["full"] }
http-body-util="0.1"

# Async
tokio       ={ version="1.39.1", features=["full"] }
tokio-util  ={ version="0.7" }
tokio-rustls={ version="0.26.0", default-features=false, features=["logging", "tls12"] }

# circuits witness generator
web-proof-circuits-witness-generator={ git="https://github.com/pluto/web-prover-circuits", rev="0a09df087612d45fa3b0d5914d93c72417edb58b" }

uuid                    ={ version="1.10.0", default-features=false, features=["v4", "serde"] }
alloy-primitives        ="0.8.2"
async-trait             ="0.1.67"
axum                    ="0.7"
axum-core               ="0.4"
base64                  ="0.22.1"
bellpepper-core         ="0.4"
bincode                 ="1.3"
byteorder               ="1.5"
bytes                   ="1"
cargo_metadata          ="0.19.1"
chrono                  ="0.4"
client-side-prover      ={ git="https://github.com/pluto/client-side-prover", rev="8e7eb839e901dcee416179116bb0f9c4f7ae683c" }
config                  ="0.14.0"
console_error_panic_hook="0.1.7"
eyre                    ="0.6.8"
ff                      ={ version="0.13", default-features=false }
futures-util            ="0.3.30"
halo2curves             ="0.6.1"
hex                     ="0.4"
http                    ="1.1"
itertools               ="0.13"
js-sys                  ="0.3.64"
k256                    ="0.13.3"
nom                     ="7.0"
num-bigint              ="0.4"
p256                    ="0.13"
pki-types               ="1.7"
regex                   ="1.11.1"
regress                 ="0.10.3"
reqwest                 ="0.12"
rs_merkle               ="1.4.2"
rustls                  ={ version="0.23.11", default-features=false }
rustls-acme             ={ version="0.10", default-features=false }
rustls-pemfile          ="2.1.2"
serde-wasm-bindgen      ="0.6.5"
serde_with              ="3.12.0"
sha1                    ="0.10"
tempdir                 ="0.3.7"
time                    ="0.3.34"
tiny-keccak             ="2.0.2"
tls-parser              ="0.12.0"
tokio-stream            ="0.1"
tokio-tungstenite       ="0.23.1"
tower                   ="0.4.13"
tower-http              ="0.5.2"
tower-service           ="0.3.2"
tracing-test            ="0.2.5"
tracing-web             ="0.1.2"
url                     ="2.5"
wasm-bindgen            ="=0.2.93"
wasm-bindgen-futures    ="=0.4.43"
wasm-bindgen-test       ="0.3.34"
webpki-roots            ="0.26.1"
ws_stream_tungstenite   ={ git="https://github.com/pluto/ws_stream_tungstenite.git", branch="latest" }

[package]
name   ="webprover"
edition="2021"

[[bin]]
name="mock_server"
path="bin/mock_server.rs"

[dependencies]
# Dependancies for the binaries

hyper         ={ workspace=true }
hyper-util    ={ workspace=true }
http-body-util={ workspace=true }
pki-types     ={ package="rustls-pki-types", version="1.7" }
rustls        ={ workspace=true, features=["logging", "tls12", "std", "ring"] }
rustls-pemfile={ workspace=true }
tokio         ={ workspace=true }
tokio-rustls  ={ workspace=true }
serde_json    ={ workspace=true }

[profile.dev]
opt-level      =1
overflow-checks=false
split-debuginfo="unpacked"
incremental    =true

[profile.release]
opt-level    =0
lto          =false
codegen-units=1
panic        ="abort"
strip        =true
debug        =true    # Propagate more information up through FFI

# [patch."https://github.com/pluto/web-prover-circuits"]
# web-proof-circuits-witness-generator={ path="../web-prover-circuits/witness-generator" }
