[package]
name   ="proofs"
version="0.1.0"
edition="2021"

[dependencies]
nova-scotia={ path="Nova-Scotia" }
# bellperson ={ version="0.25", default-features=false }
serde     ="1.0.210"
serde_json="1.0.128"
nova-snark={ version="0.37.0", default-features=false }
clap      ={ version="4.5.16", features=["derive"] }
