[package]
name   ="proofs"
version="0.1.0"
edition="2021"

[dependencies]
nova-scotia={ git="https://github.com/nalinbhardwaj/Nova-Scotia.git" }
bellperson ={ version="0.25", default-features=false }
serde_json ="1.0.128"
nova-snark ="0.23.0"
