name: Build Client WASM

on:
  workflow_call:
    inputs:
      web-prover-circuits-cache-key:
        required: true
        type: string

jobs:
  build:
    name: build client wasm
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        if: ${{ env.ACT }}
      - run: apt-get update && apt-get install -y clang
        if: ${{ env.ACT }}

      - uses: ./.github/actions/setup-rust-ubuntu
        with:
          rust-cache-key: client_wasm

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install WASM Rust components
        run: |
          rustup component add rust-src --toolchain nightly-2024-10-28
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          rustup target add wasm32-unknown-unknown --toolchain nightly-2024-10-28

      - name: Fetch web-prover-circuits cache
        if: ${{ !env.ACT }}
        uses: actions/cache/restore@v4
        with:
          path: proofs/web_proof_circuits
          key: ${{ inputs.web-prover-circuits-cache-key }}

      - run: make artifacts

      - name: Build WASM module
        run: |
          (cd client_wasm/demo/static && rm -rf build && ln -s ../../../proofs/web_proof_circuits build)
          cd client_wasm
          wasm-pack build --release --target web ./ -- -Z build-std=panic_abort,std

      - uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: "client.wasm"
          path: "client_wasm/pkg/*"
          retention-days: 7
          if-no-files-found: "error"