name: Semver Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [proofs, notary, client, client_ios, client_wasm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check semver for ${{ matrix.crate }}
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: ${{ matrix.crate }}
          manifest-path: ${{ matrix.crate }}/Cargo.toml
          # This sets the baseline (previous version) to the one specified in the root Cargo.toml file
          baseline-root: "."